artifact_uri: /Users/olaluwoyeolalekantaofeek/Downloads/fraud-detection-ml/${MLFLOW_TRACKING_URI:-file:mlruns}/0/66f02feed62144db8d439baa0688f843/artifacts
end_time: 1760825796712
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 66f02feed62144db8d439baa0688f843
run_name: receptive-elk-621
run_uuid: 66f02feed62144db8d439baa0688f843
source_name: ''
source_type: 4
source_version: ''
start_time: 1760825792130
status: 3
tags: []
user_id: olaluwoyeolalekantaofeek
